[app]
name = "cardBattle"
version = "0.0.1"
host = "localhost"
port = 8000
port_rest = 8080
dirhost = "files"

[game]
level = 1
cash = 180
exp = 125
card = 4
deck = 4
reserve = 8

[shop]
total = 1
min = 5
max = 50
time = 30
max_item = 5
url = "http://10.10.30.122:8080/"

[room]
expired_time = 30
default_max_player = 2
default_max_player_deck = 12
default_current_deployment = 2
default_max_deployment = 6
default_each_player_health = 500
default_cool_down_time = 30
default_max_card_reward = 4
default_cash_reward = 220
default_exp_reward = 100