// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cardBattle.proto

package cardBattle

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Player struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Avatar               string   `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Level                int32    `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	Cash                 int64    `protobuf:"varint,5,opt,name=cash,proto3" json:"cash,omitempty"`
	Exp                  int64    `protobuf:"varint,6,opt,name=exp,proto3" json:"exp,omitempty"`
	MaxExp               int64    `protobuf:"varint,7,opt,name=maxExp,proto3" json:"maxExp,omitempty"`
	MaxReserveSlot       int32    `protobuf:"varint,8,opt,name=maxReserveSlot,proto3" json:"maxReserveSlot,omitempty"`
	MaxDeckSlot          int32    `protobuf:"varint,9,opt,name=maxDeckSlot,proto3" json:"maxDeckSlot,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7a24134b7ec3988, []int{0}
}

func (m *Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player.Unmarshal(m, b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player.Marshal(b, m, deterministic)
}
func (m *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(m, src)
}
func (m *Player) XXX_Size() int {
	return xxx_messageInfo_Player.Size(m)
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

func (m *Player) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Player) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Player) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *Player) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *Player) GetCash() int64 {
	if m != nil {
		return m.Cash
	}
	return 0
}

func (m *Player) GetExp() int64 {
	if m != nil {
		return m.Exp
	}
	return 0
}

func (m *Player) GetMaxExp() int64 {
	if m != nil {
		return m.MaxExp
	}
	return 0
}

func (m *Player) GetMaxReserveSlot() int32 {
	if m != nil {
		return m.MaxReserveSlot
	}
	return 0
}

func (m *Player) GetMaxDeckSlot() int32 {
	if m != nil {
		return m.MaxDeckSlot
	}
	return 0
}

type AllPlayer struct {
	Players              []*Player `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AllPlayer) Reset()         { *m = AllPlayer{} }
func (m *AllPlayer) String() string { return proto.CompactTextString(m) }
func (*AllPlayer) ProtoMessage()    {}
func (*AllPlayer) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7a24134b7ec3988, []int{1}
}

func (m *AllPlayer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllPlayer.Unmarshal(m, b)
}
func (m *AllPlayer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllPlayer.Marshal(b, m, deterministic)
}
func (m *AllPlayer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllPlayer.Merge(m, src)
}
func (m *AllPlayer) XXX_Size() int {
	return xxx_messageInfo_AllPlayer.Size(m)
}
func (m *AllPlayer) XXX_DiscardUnknown() {
	xxx_messageInfo_AllPlayer.DiscardUnknown(m)
}

var xxx_messageInfo_AllPlayer proto.InternalMessageInfo

func (m *AllPlayer) GetPlayers() []*Player {
	if m != nil {
		return m.Players
	}
	return nil
}

type Card struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Image                string   `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Price                int64    `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Level                int32    `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	Atk                  int64    `protobuf:"varint,5,opt,name=atk,proto3" json:"atk,omitempty"`
	Def                  int64    `protobuf:"varint,6,opt,name=def,proto3" json:"def,omitempty"`
	Color                int32    `protobuf:"varint,7,opt,name=color,proto3" json:"color,omitempty"`
	Name                 string   `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Card) Reset()         { *m = Card{} }
func (m *Card) String() string { return proto.CompactTextString(m) }
func (*Card) ProtoMessage()    {}
func (*Card) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7a24134b7ec3988, []int{2}
}

func (m *Card) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Card.Unmarshal(m, b)
}
func (m *Card) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Card.Marshal(b, m, deterministic)
}
func (m *Card) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Card.Merge(m, src)
}
func (m *Card) XXX_Size() int {
	return xxx_messageInfo_Card.Size(m)
}
func (m *Card) XXX_DiscardUnknown() {
	xxx_messageInfo_Card.DiscardUnknown(m)
}

var xxx_messageInfo_Card proto.InternalMessageInfo

func (m *Card) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Card) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *Card) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Card) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *Card) GetAtk() int64 {
	if m != nil {
		return m.Atk
	}
	return 0
}

func (m *Card) GetDef() int64 {
	if m != nil {
		return m.Def
	}
	return 0
}

func (m *Card) GetColor() int32 {
	if m != nil {
		return m.Color
	}
	return 0
}

func (m *Card) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type AllCard struct {
	Cards                []*Card  `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AllCard) Reset()         { *m = AllCard{} }
func (m *AllCard) String() string { return proto.CompactTextString(m) }
func (*AllCard) ProtoMessage()    {}
func (*AllCard) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7a24134b7ec3988, []int{3}
}

func (m *AllCard) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllCard.Unmarshal(m, b)
}
func (m *AllCard) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllCard.Marshal(b, m, deterministic)
}
func (m *AllCard) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllCard.Merge(m, src)
}
func (m *AllCard) XXX_Size() int {
	return xxx_messageInfo_AllCard.Size(m)
}
func (m *AllCard) XXX_DiscardUnknown() {
	xxx_messageInfo_AllCard.DiscardUnknown(m)
}

var xxx_messageInfo_AllCard proto.InternalMessageInfo

func (m *AllCard) GetCards() []*Card {
	if m != nil {
		return m.Cards
	}
	return nil
}

type PlayerAndCard struct {
	Client               *Player  `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	CardData             *Card    `protobuf:"bytes,2,opt,name=cardData,proto3" json:"cardData,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerAndCard) Reset()         { *m = PlayerAndCard{} }
func (m *PlayerAndCard) String() string { return proto.CompactTextString(m) }
func (*PlayerAndCard) ProtoMessage()    {}
func (*PlayerAndCard) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7a24134b7ec3988, []int{4}
}

func (m *PlayerAndCard) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerAndCard.Unmarshal(m, b)
}
func (m *PlayerAndCard) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerAndCard.Marshal(b, m, deterministic)
}
func (m *PlayerAndCard) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerAndCard.Merge(m, src)
}
func (m *PlayerAndCard) XXX_Size() int {
	return xxx_messageInfo_PlayerAndCard.Size(m)
}
func (m *PlayerAndCard) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerAndCard.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerAndCard proto.InternalMessageInfo

func (m *PlayerAndCard) GetClient() *Player {
	if m != nil {
		return m.Client
	}
	return nil
}

func (m *PlayerAndCard) GetCardData() *Card {
	if m != nil {
		return m.CardData
	}
	return nil
}

type PlayerAndSlot struct {
	Owner                *Player  `protobuf:"bytes,1,opt,name=Owner,proto3" json:"Owner,omitempty"`
	SlotType             int32    `protobuf:"varint,2,opt,name=slotType,proto3" json:"slotType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerAndSlot) Reset()         { *m = PlayerAndSlot{} }
func (m *PlayerAndSlot) String() string { return proto.CompactTextString(m) }
func (*PlayerAndSlot) ProtoMessage()    {}
func (*PlayerAndSlot) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7a24134b7ec3988, []int{5}
}

func (m *PlayerAndSlot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerAndSlot.Unmarshal(m, b)
}
func (m *PlayerAndSlot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerAndSlot.Marshal(b, m, deterministic)
}
func (m *PlayerAndSlot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerAndSlot.Merge(m, src)
}
func (m *PlayerAndSlot) XXX_Size() int {
	return xxx_messageInfo_PlayerAndSlot.Size(m)
}
func (m *PlayerAndSlot) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerAndSlot.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerAndSlot proto.InternalMessageInfo

func (m *PlayerAndSlot) GetOwner() *Player {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *PlayerAndSlot) GetSlotType() int32 {
	if m != nil {
		return m.SlotType
	}
	return 0
}

type LobbyStream struct {
	// Types that are valid to be assigned to Event:
	//	*LobbyStream_PlayerJoin
	//	*LobbyStream_PlayerLeft
	//	*LobbyStream_CreateRoom
	//	*LobbyStream_ShopRefreshTime
	//	*LobbyStream_ShopRefresh
	//	*LobbyStream_GetOneRoom
	//	*LobbyStream_GetAllRooms
	//	*LobbyStream_GetAllPlayers
	//	*LobbyStream_GetOneplayer
	//	*LobbyStream_PlayerSuccessJoin
	//	*LobbyStream_PlayerSuccessLeft
	//	*LobbyStream_OnePlayerWithCards
	//	*LobbyStream_AllCardInShopping
	//	*LobbyStream_OnBuyCard
	//	*LobbyStream_OnCardBought
	//	*LobbyStream_OnSellCard
	//	*LobbyStream_OnCardSold
	//	*LobbyStream_OnCardDeckSlot
	//	*LobbyStream_OnSuccessAddSlot
	//	*LobbyStream_AddCardToDeck
	//	*LobbyStream_RemoveCardFromDeck
	//	*LobbyStream_ExcMessage
	Event                isLobbyStream_Event `protobuf_oneof:"event"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *LobbyStream) Reset()         { *m = LobbyStream{} }
func (m *LobbyStream) String() string { return proto.CompactTextString(m) }
func (*LobbyStream) ProtoMessage()    {}
func (*LobbyStream) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7a24134b7ec3988, []int{6}
}

func (m *LobbyStream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LobbyStream.Unmarshal(m, b)
}
func (m *LobbyStream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LobbyStream.Marshal(b, m, deterministic)
}
func (m *LobbyStream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LobbyStream.Merge(m, src)
}
func (m *LobbyStream) XXX_Size() int {
	return xxx_messageInfo_LobbyStream.Size(m)
}
func (m *LobbyStream) XXX_DiscardUnknown() {
	xxx_messageInfo_LobbyStream.DiscardUnknown(m)
}

var xxx_messageInfo_LobbyStream proto.InternalMessageInfo

type isLobbyStream_Event interface {
	isLobbyStream_Event()
}

type LobbyStream_PlayerJoin struct {
	PlayerJoin *Player `protobuf:"bytes,1,opt,name=playerJoin,proto3,oneof"`
}

type LobbyStream_PlayerLeft struct {
	PlayerLeft *Player `protobuf:"bytes,2,opt,name=playerLeft,proto3,oneof"`
}

type LobbyStream_CreateRoom struct {
	CreateRoom *RoomData `protobuf:"bytes,3,opt,name=createRoom,proto3,oneof"`
}

type LobbyStream_ShopRefreshTime struct {
	ShopRefreshTime int32 `protobuf:"varint,4,opt,name=shopRefreshTime,proto3,oneof"`
}

type LobbyStream_ShopRefresh struct {
	ShopRefresh bool `protobuf:"varint,5,opt,name=shopRefresh,proto3,oneof"`
}

type LobbyStream_GetOneRoom struct {
	GetOneRoom *RoomData `protobuf:"bytes,6,opt,name=getOneRoom,proto3,oneof"`
}

type LobbyStream_GetAllRooms struct {
	GetAllRooms *AllRoom `protobuf:"bytes,7,opt,name=getAllRooms,proto3,oneof"`
}

type LobbyStream_GetAllPlayers struct {
	GetAllPlayers *AllPlayer `protobuf:"bytes,8,opt,name=getAllPlayers,proto3,oneof"`
}

type LobbyStream_GetOneplayer struct {
	GetOneplayer *Player `protobuf:"bytes,9,opt,name=getOneplayer,proto3,oneof"`
}

type LobbyStream_PlayerSuccessJoin struct {
	PlayerSuccessJoin *Player `protobuf:"bytes,10,opt,name=playerSuccessJoin,proto3,oneof"`
}

type LobbyStream_PlayerSuccessLeft struct {
	PlayerSuccessLeft *Player `protobuf:"bytes,11,opt,name=playerSuccessLeft,proto3,oneof"`
}

type LobbyStream_OnePlayerWithCards struct {
	OnePlayerWithCards *PlayerWithCards `protobuf:"bytes,12,opt,name=onePlayerWithCards,proto3,oneof"`
}

type LobbyStream_AllCardInShopping struct {
	AllCardInShopping *AllCard `protobuf:"bytes,13,opt,name=allCardInShopping,proto3,oneof"`
}

type LobbyStream_OnBuyCard struct {
	OnBuyCard *PlayerAndCard `protobuf:"bytes,14,opt,name=onBuyCard,proto3,oneof"`
}

type LobbyStream_OnCardBought struct {
	OnCardBought bool `protobuf:"varint,15,opt,name=onCardBought,proto3,oneof"`
}

type LobbyStream_OnSellCard struct {
	OnSellCard *PlayerAndCard `protobuf:"bytes,16,opt,name=onSellCard,proto3,oneof"`
}

type LobbyStream_OnCardSold struct {
	OnCardSold bool `protobuf:"varint,17,opt,name=onCardSold,proto3,oneof"`
}

type LobbyStream_OnCardDeckSlot struct {
	OnCardDeckSlot *PlayerAndSlot `protobuf:"bytes,18,opt,name=onCardDeckSlot,proto3,oneof"`
}

type LobbyStream_OnSuccessAddSlot struct {
	OnSuccessAddSlot bool `protobuf:"varint,19,opt,name=onSuccessAddSlot,proto3,oneof"`
}

type LobbyStream_AddCardToDeck struct {
	AddCardToDeck *PlayerAndCard `protobuf:"bytes,20,opt,name=addCardToDeck,proto3,oneof"`
}

type LobbyStream_RemoveCardFromDeck struct {
	RemoveCardFromDeck *PlayerAndCard `protobuf:"bytes,21,opt,name=removeCardFromDeck,proto3,oneof"`
}

type LobbyStream_ExcMessage struct {
	ExcMessage *ExceptionErrorMessage `protobuf:"bytes,22,opt,name=excMessage,proto3,oneof"`
}

func (*LobbyStream_PlayerJoin) isLobbyStream_Event() {}

func (*LobbyStream_PlayerLeft) isLobbyStream_Event() {}

func (*LobbyStream_CreateRoom) isLobbyStream_Event() {}

func (*LobbyStream_ShopRefreshTime) isLobbyStream_Event() {}

func (*LobbyStream_ShopRefresh) isLobbyStream_Event() {}

func (*LobbyStream_GetOneRoom) isLobbyStream_Event() {}

func (*LobbyStream_GetAllRooms) isLobbyStream_Event() {}

func (*LobbyStream_GetAllPlayers) isLobbyStream_Event() {}

func (*LobbyStream_GetOneplayer) isLobbyStream_Event() {}

func (*LobbyStream_PlayerSuccessJoin) isLobbyStream_Event() {}

func (*LobbyStream_PlayerSuccessLeft) isLobbyStream_Event() {}

func (*LobbyStream_OnePlayerWithCards) isLobbyStream_Event() {}

func (*LobbyStream_AllCardInShopping) isLobbyStream_Event() {}

func (*LobbyStream_OnBuyCard) isLobbyStream_Event() {}

func (*LobbyStream_OnCardBought) isLobbyStream_Event() {}

func (*LobbyStream_OnSellCard) isLobbyStream_Event() {}

func (*LobbyStream_OnCardSold) isLobbyStream_Event() {}

func (*LobbyStream_OnCardDeckSlot) isLobbyStream_Event() {}

func (*LobbyStream_OnSuccessAddSlot) isLobbyStream_Event() {}

func (*LobbyStream_AddCardToDeck) isLobbyStream_Event() {}

func (*LobbyStream_RemoveCardFromDeck) isLobbyStream_Event() {}

func (*LobbyStream_ExcMessage) isLobbyStream_Event() {}

func (m *LobbyStream) GetEvent() isLobbyStream_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *LobbyStream) GetPlayerJoin() *Player {
	if x, ok := m.GetEvent().(*LobbyStream_PlayerJoin); ok {
		return x.PlayerJoin
	}
	return nil
}

func (m *LobbyStream) GetPlayerLeft() *Player {
	if x, ok := m.GetEvent().(*LobbyStream_PlayerLeft); ok {
		return x.PlayerLeft
	}
	return nil
}

func (m *LobbyStream) GetCreateRoom() *RoomData {
	if x, ok := m.GetEvent().(*LobbyStream_CreateRoom); ok {
		return x.CreateRoom
	}
	return nil
}

func (m *LobbyStream) GetShopRefreshTime() int32 {
	if x, ok := m.GetEvent().(*LobbyStream_ShopRefreshTime); ok {
		return x.ShopRefreshTime
	}
	return 0
}

func (m *LobbyStream) GetShopRefresh() bool {
	if x, ok := m.GetEvent().(*LobbyStream_ShopRefresh); ok {
		return x.ShopRefresh
	}
	return false
}

func (m *LobbyStream) GetGetOneRoom() *RoomData {
	if x, ok := m.GetEvent().(*LobbyStream_GetOneRoom); ok {
		return x.GetOneRoom
	}
	return nil
}

func (m *LobbyStream) GetGetAllRooms() *AllRoom {
	if x, ok := m.GetEvent().(*LobbyStream_GetAllRooms); ok {
		return x.GetAllRooms
	}
	return nil
}

func (m *LobbyStream) GetGetAllPlayers() *AllPlayer {
	if x, ok := m.GetEvent().(*LobbyStream_GetAllPlayers); ok {
		return x.GetAllPlayers
	}
	return nil
}

func (m *LobbyStream) GetGetOneplayer() *Player {
	if x, ok := m.GetEvent().(*LobbyStream_GetOneplayer); ok {
		return x.GetOneplayer
	}
	return nil
}

func (m *LobbyStream) GetPlayerSuccessJoin() *Player {
	if x, ok := m.GetEvent().(*LobbyStream_PlayerSuccessJoin); ok {
		return x.PlayerSuccessJoin
	}
	return nil
}

func (m *LobbyStream) GetPlayerSuccessLeft() *Player {
	if x, ok := m.GetEvent().(*LobbyStream_PlayerSuccessLeft); ok {
		return x.PlayerSuccessLeft
	}
	return nil
}

func (m *LobbyStream) GetOnePlayerWithCards() *PlayerWithCards {
	if x, ok := m.GetEvent().(*LobbyStream_OnePlayerWithCards); ok {
		return x.OnePlayerWithCards
	}
	return nil
}

func (m *LobbyStream) GetAllCardInShopping() *AllCard {
	if x, ok := m.GetEvent().(*LobbyStream_AllCardInShopping); ok {
		return x.AllCardInShopping
	}
	return nil
}

func (m *LobbyStream) GetOnBuyCard() *PlayerAndCard {
	if x, ok := m.GetEvent().(*LobbyStream_OnBuyCard); ok {
		return x.OnBuyCard
	}
	return nil
}

func (m *LobbyStream) GetOnCardBought() bool {
	if x, ok := m.GetEvent().(*LobbyStream_OnCardBought); ok {
		return x.OnCardBought
	}
	return false
}

func (m *LobbyStream) GetOnSellCard() *PlayerAndCard {
	if x, ok := m.GetEvent().(*LobbyStream_OnSellCard); ok {
		return x.OnSellCard
	}
	return nil
}

func (m *LobbyStream) GetOnCardSold() bool {
	if x, ok := m.GetEvent().(*LobbyStream_OnCardSold); ok {
		return x.OnCardSold
	}
	return false
}

func (m *LobbyStream) GetOnCardDeckSlot() *PlayerAndSlot {
	if x, ok := m.GetEvent().(*LobbyStream_OnCardDeckSlot); ok {
		return x.OnCardDeckSlot
	}
	return nil
}

func (m *LobbyStream) GetOnSuccessAddSlot() bool {
	if x, ok := m.GetEvent().(*LobbyStream_OnSuccessAddSlot); ok {
		return x.OnSuccessAddSlot
	}
	return false
}

func (m *LobbyStream) GetAddCardToDeck() *PlayerAndCard {
	if x, ok := m.GetEvent().(*LobbyStream_AddCardToDeck); ok {
		return x.AddCardToDeck
	}
	return nil
}

func (m *LobbyStream) GetRemoveCardFromDeck() *PlayerAndCard {
	if x, ok := m.GetEvent().(*LobbyStream_RemoveCardFromDeck); ok {
		return x.RemoveCardFromDeck
	}
	return nil
}

func (m *LobbyStream) GetExcMessage() *ExceptionErrorMessage {
	if x, ok := m.GetEvent().(*LobbyStream_ExcMessage); ok {
		return x.ExcMessage
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*LobbyStream) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*LobbyStream_PlayerJoin)(nil),
		(*LobbyStream_PlayerLeft)(nil),
		(*LobbyStream_CreateRoom)(nil),
		(*LobbyStream_ShopRefreshTime)(nil),
		(*LobbyStream_ShopRefresh)(nil),
		(*LobbyStream_GetOneRoom)(nil),
		(*LobbyStream_GetAllRooms)(nil),
		(*LobbyStream_GetAllPlayers)(nil),
		(*LobbyStream_GetOneplayer)(nil),
		(*LobbyStream_PlayerSuccessJoin)(nil),
		(*LobbyStream_PlayerSuccessLeft)(nil),
		(*LobbyStream_OnePlayerWithCards)(nil),
		(*LobbyStream_AllCardInShopping)(nil),
		(*LobbyStream_OnBuyCard)(nil),
		(*LobbyStream_OnCardBought)(nil),
		(*LobbyStream_OnSellCard)(nil),
		(*LobbyStream_OnCardSold)(nil),
		(*LobbyStream_OnCardDeckSlot)(nil),
		(*LobbyStream_OnSuccessAddSlot)(nil),
		(*LobbyStream_AddCardToDeck)(nil),
		(*LobbyStream_RemoveCardFromDeck)(nil),
		(*LobbyStream_ExcMessage)(nil),
	}
}

type QueueStream struct {
	// Types that are valid to be assigned to Event:
	//	*QueueStream_OnjoinWaitingRoom
	//	*QueueStream_OnLeftWaitingRoom
	//	*QueueStream_OnBattleFound
	//	*QueueStream_OnBattleNotFound
	Event                isQueueStream_Event `protobuf_oneof:"event"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *QueueStream) Reset()         { *m = QueueStream{} }
func (m *QueueStream) String() string { return proto.CompactTextString(m) }
func (*QueueStream) ProtoMessage()    {}
func (*QueueStream) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7a24134b7ec3988, []int{7}
}

func (m *QueueStream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueueStream.Unmarshal(m, b)
}
func (m *QueueStream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueueStream.Marshal(b, m, deterministic)
}
func (m *QueueStream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueueStream.Merge(m, src)
}
func (m *QueueStream) XXX_Size() int {
	return xxx_messageInfo_QueueStream.Size(m)
}
func (m *QueueStream) XXX_DiscardUnknown() {
	xxx_messageInfo_QueueStream.DiscardUnknown(m)
}

var xxx_messageInfo_QueueStream proto.InternalMessageInfo

type isQueueStream_Event interface {
	isQueueStream_Event()
}

type QueueStream_OnjoinWaitingRoom struct {
	OnjoinWaitingRoom *Player `protobuf:"bytes,1,opt,name=onjoinWaitingRoom,proto3,oneof"`
}

type QueueStream_OnLeftWaitingRoom struct {
	OnLeftWaitingRoom *Player `protobuf:"bytes,2,opt,name=onLeftWaitingRoom,proto3,oneof"`
}

type QueueStream_OnBattleFound struct {
	OnBattleFound *RoomData `protobuf:"bytes,3,opt,name=onBattleFound,proto3,oneof"`
}

type QueueStream_OnBattleNotFound struct {
	OnBattleNotFound bool `protobuf:"varint,4,opt,name=onBattleNotFound,proto3,oneof"`
}

func (*QueueStream_OnjoinWaitingRoom) isQueueStream_Event() {}

func (*QueueStream_OnLeftWaitingRoom) isQueueStream_Event() {}

func (*QueueStream_OnBattleFound) isQueueStream_Event() {}

func (*QueueStream_OnBattleNotFound) isQueueStream_Event() {}

func (m *QueueStream) GetEvent() isQueueStream_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *QueueStream) GetOnjoinWaitingRoom() *Player {
	if x, ok := m.GetEvent().(*QueueStream_OnjoinWaitingRoom); ok {
		return x.OnjoinWaitingRoom
	}
	return nil
}

func (m *QueueStream) GetOnLeftWaitingRoom() *Player {
	if x, ok := m.GetEvent().(*QueueStream_OnLeftWaitingRoom); ok {
		return x.OnLeftWaitingRoom
	}
	return nil
}

func (m *QueueStream) GetOnBattleFound() *RoomData {
	if x, ok := m.GetEvent().(*QueueStream_OnBattleFound); ok {
		return x.OnBattleFound
	}
	return nil
}

func (m *QueueStream) GetOnBattleNotFound() bool {
	if x, ok := m.GetEvent().(*QueueStream_OnBattleNotFound); ok {
		return x.OnBattleNotFound
	}
	return false
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*QueueStream) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*QueueStream_OnjoinWaitingRoom)(nil),
		(*QueueStream_OnLeftWaitingRoom)(nil),
		(*QueueStream_OnBattleFound)(nil),
		(*QueueStream_OnBattleNotFound)(nil),
	}
}

type PlayerWithCards struct {
	Owner                *Player  `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Deck                 []*Card  `protobuf:"bytes,2,rep,name=deck,proto3" json:"deck,omitempty"`
	Deployed             []*Card  `protobuf:"bytes,3,rep,name=deployed,proto3" json:"deployed,omitempty"`
	Reserve              []*Card  `protobuf:"bytes,4,rep,name=reserve,proto3" json:"reserve,omitempty"`
	Hp                   int64    `protobuf:"varint,5,opt,name=hp,proto3" json:"hp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerWithCards) Reset()         { *m = PlayerWithCards{} }
func (m *PlayerWithCards) String() string { return proto.CompactTextString(m) }
func (*PlayerWithCards) ProtoMessage()    {}
func (*PlayerWithCards) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7a24134b7ec3988, []int{8}
}

func (m *PlayerWithCards) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerWithCards.Unmarshal(m, b)
}
func (m *PlayerWithCards) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerWithCards.Marshal(b, m, deterministic)
}
func (m *PlayerWithCards) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerWithCards.Merge(m, src)
}
func (m *PlayerWithCards) XXX_Size() int {
	return xxx_messageInfo_PlayerWithCards.Size(m)
}
func (m *PlayerWithCards) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerWithCards.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerWithCards proto.InternalMessageInfo

func (m *PlayerWithCards) GetOwner() *Player {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *PlayerWithCards) GetDeck() []*Card {
	if m != nil {
		return m.Deck
	}
	return nil
}

func (m *PlayerWithCards) GetDeployed() []*Card {
	if m != nil {
		return m.Deployed
	}
	return nil
}

func (m *PlayerWithCards) GetReserve() []*Card {
	if m != nil {
		return m.Reserve
	}
	return nil
}

func (m *PlayerWithCards) GetHp() int64 {
	if m != nil {
		return m.Hp
	}
	return 0
}

type AllPlayerWithCards struct {
	Players              []*PlayerWithCards `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *AllPlayerWithCards) Reset()         { *m = AllPlayerWithCards{} }
func (m *AllPlayerWithCards) String() string { return proto.CompactTextString(m) }
func (*AllPlayerWithCards) ProtoMessage()    {}
func (*AllPlayerWithCards) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7a24134b7ec3988, []int{9}
}

func (m *AllPlayerWithCards) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllPlayerWithCards.Unmarshal(m, b)
}
func (m *AllPlayerWithCards) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllPlayerWithCards.Marshal(b, m, deterministic)
}
func (m *AllPlayerWithCards) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllPlayerWithCards.Merge(m, src)
}
func (m *AllPlayerWithCards) XXX_Size() int {
	return xxx_messageInfo_AllPlayerWithCards.Size(m)
}
func (m *AllPlayerWithCards) XXX_DiscardUnknown() {
	xxx_messageInfo_AllPlayerWithCards.DiscardUnknown(m)
}

var xxx_messageInfo_AllPlayerWithCards proto.InternalMessageInfo

func (m *AllPlayerWithCards) GetPlayers() []*PlayerWithCards {
	if m != nil {
		return m.Players
	}
	return nil
}

type RoomData struct {
	Id                   string             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RoomName             string             `protobuf:"bytes,2,opt,name=roomName,proto3" json:"roomName,omitempty"`
	Players              []*PlayerWithCards `protobuf:"bytes,4,rep,name=players,proto3" json:"players,omitempty"`
	MaxPlayer            int32              `protobuf:"varint,5,opt,name=maxPlayer,proto3" json:"maxPlayer,omitempty"`
	MaxPlayerDeck        int32              `protobuf:"varint,6,opt,name=maxPlayerDeck,proto3" json:"maxPlayerDeck,omitempty"`
	MaxCurrentDeployment int32              `protobuf:"varint,7,opt,name=maxCurrentDeployment,proto3" json:"maxCurrentDeployment,omitempty"`
	MaxDeployment        int32              `protobuf:"varint,8,opt,name=maxDeployment,proto3" json:"maxDeployment,omitempty"`
	EachPlayerHealth     int64              `protobuf:"varint,9,opt,name=eachPlayerHealth,proto3" json:"eachPlayerHealth,omitempty"`
	CoolDownTime         int32              `protobuf:"varint,10,opt,name=coolDownTime,proto3" json:"coolDownTime,omitempty"`
	Reward               *RoomReward        `protobuf:"bytes,11,opt,name=reward,proto3" json:"reward,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *RoomData) Reset()         { *m = RoomData{} }
func (m *RoomData) String() string { return proto.CompactTextString(m) }
func (*RoomData) ProtoMessage()    {}
func (*RoomData) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7a24134b7ec3988, []int{10}
}

func (m *RoomData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomData.Unmarshal(m, b)
}
func (m *RoomData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomData.Marshal(b, m, deterministic)
}
func (m *RoomData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomData.Merge(m, src)
}
func (m *RoomData) XXX_Size() int {
	return xxx_messageInfo_RoomData.Size(m)
}
func (m *RoomData) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomData.DiscardUnknown(m)
}

var xxx_messageInfo_RoomData proto.InternalMessageInfo

func (m *RoomData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RoomData) GetRoomName() string {
	if m != nil {
		return m.RoomName
	}
	return ""
}

func (m *RoomData) GetPlayers() []*PlayerWithCards {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *RoomData) GetMaxPlayer() int32 {
	if m != nil {
		return m.MaxPlayer
	}
	return 0
}

func (m *RoomData) GetMaxPlayerDeck() int32 {
	if m != nil {
		return m.MaxPlayerDeck
	}
	return 0
}

func (m *RoomData) GetMaxCurrentDeployment() int32 {
	if m != nil {
		return m.MaxCurrentDeployment
	}
	return 0
}

func (m *RoomData) GetMaxDeployment() int32 {
	if m != nil {
		return m.MaxDeployment
	}
	return 0
}

func (m *RoomData) GetEachPlayerHealth() int64 {
	if m != nil {
		return m.EachPlayerHealth
	}
	return 0
}

func (m *RoomData) GetCoolDownTime() int32 {
	if m != nil {
		return m.CoolDownTime
	}
	return 0
}

func (m *RoomData) GetReward() *RoomReward {
	if m != nil {
		return m.Reward
	}
	return nil
}

type RoomReward struct {
	CardReward           []*Card  `protobuf:"bytes,1,rep,name=cardReward,proto3" json:"cardReward,omitempty"`
	CashReward           int64    `protobuf:"varint,2,opt,name=cashReward,proto3" json:"cashReward,omitempty"`
	ExpReward            int64    `protobuf:"varint,3,opt,name=expReward,proto3" json:"expReward,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomReward) Reset()         { *m = RoomReward{} }
func (m *RoomReward) String() string { return proto.CompactTextString(m) }
func (*RoomReward) ProtoMessage()    {}
func (*RoomReward) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7a24134b7ec3988, []int{11}
}

func (m *RoomReward) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomReward.Unmarshal(m, b)
}
func (m *RoomReward) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomReward.Marshal(b, m, deterministic)
}
func (m *RoomReward) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomReward.Merge(m, src)
}
func (m *RoomReward) XXX_Size() int {
	return xxx_messageInfo_RoomReward.Size(m)
}
func (m *RoomReward) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomReward.DiscardUnknown(m)
}

var xxx_messageInfo_RoomReward proto.InternalMessageInfo

func (m *RoomReward) GetCardReward() []*Card {
	if m != nil {
		return m.CardReward
	}
	return nil
}

func (m *RoomReward) GetCashReward() int64 {
	if m != nil {
		return m.CashReward
	}
	return 0
}

func (m *RoomReward) GetExpReward() int64 {
	if m != nil {
		return m.ExpReward
	}
	return 0
}

type AllRoom struct {
	Rooms                []*RoomData `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AllRoom) Reset()         { *m = AllRoom{} }
func (m *AllRoom) String() string { return proto.CompactTextString(m) }
func (*AllRoom) ProtoMessage()    {}
func (*AllRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7a24134b7ec3988, []int{12}
}

func (m *AllRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllRoom.Unmarshal(m, b)
}
func (m *AllRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllRoom.Marshal(b, m, deterministic)
}
func (m *AllRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllRoom.Merge(m, src)
}
func (m *AllRoom) XXX_Size() int {
	return xxx_messageInfo_AllRoom.Size(m)
}
func (m *AllRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_AllRoom.DiscardUnknown(m)
}

var xxx_messageInfo_AllRoom proto.InternalMessageInfo

func (m *AllRoom) GetRooms() []*RoomData {
	if m != nil {
		return m.Rooms
	}
	return nil
}

type PlayerBattleResult struct {
	Owner                *Player  `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	DamageReceive        int64    `protobuf:"varint,2,opt,name=damageReceive,proto3" json:"damageReceive,omitempty"`
	EnemyAtk             int64    `protobuf:"varint,3,opt,name=enemyAtk,proto3" json:"enemyAtk,omitempty"`
	OwnerDef             int64    `protobuf:"varint,4,opt,name=ownerDef,proto3" json:"ownerDef,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerBattleResult) Reset()         { *m = PlayerBattleResult{} }
func (m *PlayerBattleResult) String() string { return proto.CompactTextString(m) }
func (*PlayerBattleResult) ProtoMessage()    {}
func (*PlayerBattleResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7a24134b7ec3988, []int{13}
}

func (m *PlayerBattleResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerBattleResult.Unmarshal(m, b)
}
func (m *PlayerBattleResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerBattleResult.Marshal(b, m, deterministic)
}
func (m *PlayerBattleResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerBattleResult.Merge(m, src)
}
func (m *PlayerBattleResult) XXX_Size() int {
	return xxx_messageInfo_PlayerBattleResult.Size(m)
}
func (m *PlayerBattleResult) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerBattleResult.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerBattleResult proto.InternalMessageInfo

func (m *PlayerBattleResult) GetOwner() *Player {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *PlayerBattleResult) GetDamageReceive() int64 {
	if m != nil {
		return m.DamageReceive
	}
	return 0
}

func (m *PlayerBattleResult) GetEnemyAtk() int64 {
	if m != nil {
		return m.EnemyAtk
	}
	return 0
}

func (m *PlayerBattleResult) GetOwnerDef() int64 {
	if m != nil {
		return m.OwnerDef
	}
	return 0
}

type EndResult struct {
	Winner          *Player               `protobuf:"bytes,1,opt,name=winner,proto3" json:"winner,omitempty"`
	AllBattleResult []*PlayerBattleResult `protobuf:"bytes,2,rep,name=allBattleResult,proto3" json:"allBattleResult,omitempty"`
	// for flagging winning status
	// 0 = is enemy player hp is 0
	// 1 = is enemy card is 0
	// 2 = is enemy hp is lower
	FlagResult           int32       `protobuf:"varint,3,opt,name=flagResult,proto3" json:"flagResult,omitempty"`
	Reward               *RoomReward `protobuf:"bytes,4,opt,name=reward,proto3" json:"reward,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *EndResult) Reset()         { *m = EndResult{} }
func (m *EndResult) String() string { return proto.CompactTextString(m) }
func (*EndResult) ProtoMessage()    {}
func (*EndResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7a24134b7ec3988, []int{14}
}

func (m *EndResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EndResult.Unmarshal(m, b)
}
func (m *EndResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EndResult.Marshal(b, m, deterministic)
}
func (m *EndResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndResult.Merge(m, src)
}
func (m *EndResult) XXX_Size() int {
	return xxx_messageInfo_EndResult.Size(m)
}
func (m *EndResult) XXX_DiscardUnknown() {
	xxx_messageInfo_EndResult.DiscardUnknown(m)
}

var xxx_messageInfo_EndResult proto.InternalMessageInfo

func (m *EndResult) GetWinner() *Player {
	if m != nil {
		return m.Winner
	}
	return nil
}

func (m *EndResult) GetAllBattleResult() []*PlayerBattleResult {
	if m != nil {
		return m.AllBattleResult
	}
	return nil
}

func (m *EndResult) GetFlagResult() int32 {
	if m != nil {
		return m.FlagResult
	}
	return 0
}

func (m *EndResult) GetReward() *RoomReward {
	if m != nil {
		return m.Reward
	}
	return nil
}

type AllPlayerBattleResult struct {
	Results              []*PlayerBattleResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *AllPlayerBattleResult) Reset()         { *m = AllPlayerBattleResult{} }
func (m *AllPlayerBattleResult) String() string { return proto.CompactTextString(m) }
func (*AllPlayerBattleResult) ProtoMessage()    {}
func (*AllPlayerBattleResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7a24134b7ec3988, []int{15}
}

func (m *AllPlayerBattleResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllPlayerBattleResult.Unmarshal(m, b)
}
func (m *AllPlayerBattleResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllPlayerBattleResult.Marshal(b, m, deterministic)
}
func (m *AllPlayerBattleResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllPlayerBattleResult.Merge(m, src)
}
func (m *AllPlayerBattleResult) XXX_Size() int {
	return xxx_messageInfo_AllPlayerBattleResult.Size(m)
}
func (m *AllPlayerBattleResult) XXX_DiscardUnknown() {
	xxx_messageInfo_AllPlayerBattleResult.DiscardUnknown(m)
}

var xxx_messageInfo_AllPlayerBattleResult proto.InternalMessageInfo

func (m *AllPlayerBattleResult) GetResults() []*PlayerBattleResult {
	if m != nil {
		return m.Results
	}
	return nil
}

type RoomStream struct {
	// Types that are valid to be assigned to Event:
	//	*RoomStream_PlayerJoin
	//	*RoomStream_PlayerLeft
	//	*RoomStream_OnRoomUpdate
	//	*RoomStream_CountDown
	//	*RoomStream_BattleResult
	//	*RoomStream_Result
	//	*RoomStream_OnDraw
	//	*RoomStream_DeployCard
	//	*RoomStream_PickupCard
	//	*RoomStream_GetOneRoom
	//	*RoomStream_ExcMessage
	Event isRoomStream_Event `protobuf_oneof:"event"`
	// for flagging in server
	// 0 = room is good to go
	// 1 = room must be stoped
	RoomFlag int32 `protobuf:"varint,12,opt,name=roomFlag,proto3" json:"roomFlag,omitempty"`
	// for flagging in server and client
	// 0 = all player is not ready
	// 1 = all player is ready
	// 2 = only some player ready
	PlayersFlag int32 `protobuf:"varint,13,opt,name=playersFlag,proto3" json:"playersFlag,omitempty"`
	// for flagging in server
	// 0 = battle countdown is good to go
	// 1 = battle countdown must stop
	BattleFlag int32 `protobuf:"varint,14,opt,name=battleFlag,proto3" json:"battleFlag,omitempty"`
	// for join and leave
	// this for identifier
	IdRoom               string   `protobuf:"bytes,15,opt,name=idRoom,proto3" json:"idRoom,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomStream) Reset()         { *m = RoomStream{} }
func (m *RoomStream) String() string { return proto.CompactTextString(m) }
func (*RoomStream) ProtoMessage()    {}
func (*RoomStream) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7a24134b7ec3988, []int{16}
}

func (m *RoomStream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomStream.Unmarshal(m, b)
}
func (m *RoomStream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomStream.Marshal(b, m, deterministic)
}
func (m *RoomStream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomStream.Merge(m, src)
}
func (m *RoomStream) XXX_Size() int {
	return xxx_messageInfo_RoomStream.Size(m)
}
func (m *RoomStream) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomStream.DiscardUnknown(m)
}

var xxx_messageInfo_RoomStream proto.InternalMessageInfo

type isRoomStream_Event interface {
	isRoomStream_Event()
}

type RoomStream_PlayerJoin struct {
	PlayerJoin *PlayerWithCards `protobuf:"bytes,1,opt,name=playerJoin,proto3,oneof"`
}

type RoomStream_PlayerLeft struct {
	PlayerLeft *PlayerWithCards `protobuf:"bytes,2,opt,name=playerLeft,proto3,oneof"`
}

type RoomStream_OnRoomUpdate struct {
	OnRoomUpdate *RoomData `protobuf:"bytes,3,opt,name=onRoomUpdate,proto3,oneof"`
}

type RoomStream_CountDown struct {
	CountDown int32 `protobuf:"varint,4,opt,name=countDown,proto3,oneof"`
}

type RoomStream_BattleResult struct {
	BattleResult *AllPlayerBattleResult `protobuf:"bytes,5,opt,name=battleResult,proto3,oneof"`
}

type RoomStream_Result struct {
	Result *EndResult `protobuf:"bytes,6,opt,name=result,proto3,oneof"`
}

type RoomStream_OnDraw struct {
	OnDraw int32 `protobuf:"varint,7,opt,name=onDraw,proto3,oneof"`
}

type RoomStream_DeployCard struct {
	DeployCard *PlayerAndCard `protobuf:"bytes,8,opt,name=deployCard,proto3,oneof"`
}

type RoomStream_PickupCard struct {
	PickupCard *PlayerAndCard `protobuf:"bytes,9,opt,name=pickupCard,proto3,oneof"`
}

type RoomStream_GetOneRoom struct {
	GetOneRoom *RoomData `protobuf:"bytes,10,opt,name=getOneRoom,proto3,oneof"`
}

type RoomStream_ExcMessage struct {
	ExcMessage *ExceptionErrorMessage `protobuf:"bytes,11,opt,name=excMessage,proto3,oneof"`
}

func (*RoomStream_PlayerJoin) isRoomStream_Event() {}

func (*RoomStream_PlayerLeft) isRoomStream_Event() {}

func (*RoomStream_OnRoomUpdate) isRoomStream_Event() {}

func (*RoomStream_CountDown) isRoomStream_Event() {}

func (*RoomStream_BattleResult) isRoomStream_Event() {}

func (*RoomStream_Result) isRoomStream_Event() {}

func (*RoomStream_OnDraw) isRoomStream_Event() {}

func (*RoomStream_DeployCard) isRoomStream_Event() {}

func (*RoomStream_PickupCard) isRoomStream_Event() {}

func (*RoomStream_GetOneRoom) isRoomStream_Event() {}

func (*RoomStream_ExcMessage) isRoomStream_Event() {}

func (m *RoomStream) GetEvent() isRoomStream_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *RoomStream) GetPlayerJoin() *PlayerWithCards {
	if x, ok := m.GetEvent().(*RoomStream_PlayerJoin); ok {
		return x.PlayerJoin
	}
	return nil
}

func (m *RoomStream) GetPlayerLeft() *PlayerWithCards {
	if x, ok := m.GetEvent().(*RoomStream_PlayerLeft); ok {
		return x.PlayerLeft
	}
	return nil
}

func (m *RoomStream) GetOnRoomUpdate() *RoomData {
	if x, ok := m.GetEvent().(*RoomStream_OnRoomUpdate); ok {
		return x.OnRoomUpdate
	}
	return nil
}

func (m *RoomStream) GetCountDown() int32 {
	if x, ok := m.GetEvent().(*RoomStream_CountDown); ok {
		return x.CountDown
	}
	return 0
}

func (m *RoomStream) GetBattleResult() *AllPlayerBattleResult {
	if x, ok := m.GetEvent().(*RoomStream_BattleResult); ok {
		return x.BattleResult
	}
	return nil
}

func (m *RoomStream) GetResult() *EndResult {
	if x, ok := m.GetEvent().(*RoomStream_Result); ok {
		return x.Result
	}
	return nil
}

func (m *RoomStream) GetOnDraw() int32 {
	if x, ok := m.GetEvent().(*RoomStream_OnDraw); ok {
		return x.OnDraw
	}
	return 0
}

func (m *RoomStream) GetDeployCard() *PlayerAndCard {
	if x, ok := m.GetEvent().(*RoomStream_DeployCard); ok {
		return x.DeployCard
	}
	return nil
}

func (m *RoomStream) GetPickupCard() *PlayerAndCard {
	if x, ok := m.GetEvent().(*RoomStream_PickupCard); ok {
		return x.PickupCard
	}
	return nil
}

func (m *RoomStream) GetGetOneRoom() *RoomData {
	if x, ok := m.GetEvent().(*RoomStream_GetOneRoom); ok {
		return x.GetOneRoom
	}
	return nil
}

func (m *RoomStream) GetExcMessage() *ExceptionErrorMessage {
	if x, ok := m.GetEvent().(*RoomStream_ExcMessage); ok {
		return x.ExcMessage
	}
	return nil
}

func (m *RoomStream) GetRoomFlag() int32 {
	if m != nil {
		return m.RoomFlag
	}
	return 0
}

func (m *RoomStream) GetPlayersFlag() int32 {
	if m != nil {
		return m.PlayersFlag
	}
	return 0
}

func (m *RoomStream) GetBattleFlag() int32 {
	if m != nil {
		return m.BattleFlag
	}
	return 0
}

func (m *RoomStream) GetIdRoom() string {
	if m != nil {
		return m.IdRoom
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*RoomStream) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*RoomStream_PlayerJoin)(nil),
		(*RoomStream_PlayerLeft)(nil),
		(*RoomStream_OnRoomUpdate)(nil),
		(*RoomStream_CountDown)(nil),
		(*RoomStream_BattleResult)(nil),
		(*RoomStream_Result)(nil),
		(*RoomStream_OnDraw)(nil),
		(*RoomStream_DeployCard)(nil),
		(*RoomStream_PickupCard)(nil),
		(*RoomStream_GetOneRoom)(nil),
		(*RoomStream_ExcMessage)(nil),
	}
}

type ExceptionErrorMessage struct {
	ExceptionMessage     string   `protobuf:"bytes,1,opt,name=exceptionMessage,proto3" json:"exceptionMessage,omitempty"`
	ExceptionFlag        int32    `protobuf:"varint,2,opt,name=exceptionFlag,proto3" json:"exceptionFlag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExceptionErrorMessage) Reset()         { *m = ExceptionErrorMessage{} }
func (m *ExceptionErrorMessage) String() string { return proto.CompactTextString(m) }
func (*ExceptionErrorMessage) ProtoMessage()    {}
func (*ExceptionErrorMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7a24134b7ec3988, []int{17}
}

func (m *ExceptionErrorMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExceptionErrorMessage.Unmarshal(m, b)
}
func (m *ExceptionErrorMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExceptionErrorMessage.Marshal(b, m, deterministic)
}
func (m *ExceptionErrorMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExceptionErrorMessage.Merge(m, src)
}
func (m *ExceptionErrorMessage) XXX_Size() int {
	return xxx_messageInfo_ExceptionErrorMessage.Size(m)
}
func (m *ExceptionErrorMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ExceptionErrorMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ExceptionErrorMessage proto.InternalMessageInfo

func (m *ExceptionErrorMessage) GetExceptionMessage() string {
	if m != nil {
		return m.ExceptionMessage
	}
	return ""
}

func (m *ExceptionErrorMessage) GetExceptionFlag() int32 {
	if m != nil {
		return m.ExceptionFlag
	}
	return 0
}

func init() {
	proto.RegisterType((*Player)(nil), "cardBattle.player")
	proto.RegisterType((*AllPlayer)(nil), "cardBattle.allPlayer")
	proto.RegisterType((*Card)(nil), "cardBattle.card")
	proto.RegisterType((*AllCard)(nil), "cardBattle.allCard")
	proto.RegisterType((*PlayerAndCard)(nil), "cardBattle.playerAndCard")
	proto.RegisterType((*PlayerAndSlot)(nil), "cardBattle.playerAndSlot")
	proto.RegisterType((*LobbyStream)(nil), "cardBattle.lobbyStream")
	proto.RegisterType((*QueueStream)(nil), "cardBattle.queueStream")
	proto.RegisterType((*PlayerWithCards)(nil), "cardBattle.playerWithCards")
	proto.RegisterType((*AllPlayerWithCards)(nil), "cardBattle.allPlayerWithCards")
	proto.RegisterType((*RoomData)(nil), "cardBattle.roomData")
	proto.RegisterType((*RoomReward)(nil), "cardBattle.roomReward")
	proto.RegisterType((*AllRoom)(nil), "cardBattle.allRoom")
	proto.RegisterType((*PlayerBattleResult)(nil), "cardBattle.playerBattleResult")
	proto.RegisterType((*EndResult)(nil), "cardBattle.endResult")
	proto.RegisterType((*AllPlayerBattleResult)(nil), "cardBattle.allPlayerBattleResult")
	proto.RegisterType((*RoomStream)(nil), "cardBattle.roomStream")
	proto.RegisterType((*ExceptionErrorMessage)(nil), "cardBattle.exceptionErrorMessage")
}

func init() { proto.RegisterFile("cardBattle.proto", fileDescriptor_a7a24134b7ec3988) }

var fileDescriptor_a7a24134b7ec3988 = []byte{
	// 1569 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x58, 0xcd, 0x72, 0x1b, 0x45,
	0x10, 0xd6, 0x8f, 0x25, 0x4b, 0x2d, 0xcb, 0x3f, 0x13, 0xdb, 0x2c, 0x86, 0x4a, 0x99, 0xad, 0x54,
	0xca, 0xe5, 0x4a, 0x85, 0x60, 0x08, 0x24, 0x84, 0x1c, 0xfc, 0x93, 0x20, 0xc8, 0xff, 0x38, 0xa9,
	0x9c, 0xc7, 0xbb, 0x63, 0x69, 0xf1, 0xee, 0xce, 0xb2, 0x5a, 0xd9, 0x72, 0x15, 0x4f, 0x00, 0x2f,
	0xc0, 0x81, 0x33, 0xcf, 0xc1, 0x9d, 0x13, 0xaf, 0xc0, 0x13, 0xf0, 0x08, 0xd4, 0xf4, 0x8c, 0x76,
	0x47, 0xda, 0xd5, 0x0f, 0xdc, 0xb6, 0xbf, 0xfe, 0xba, 0xa7, 0xa7, 0x7b, 0x66, 0xba, 0x25, 0x58,
	0x77, 0x58, 0xec, 0x1e, 0xb1, 0x24, 0xf1, 0xf9, 0xdd, 0x28, 0x16, 0x89, 0x20, 0x90, 0x21, 0xf6,
	0xdf, 0x65, 0xa8, 0x47, 0x3e, 0xbb, 0xe6, 0x31, 0x59, 0x85, 0x8a, 0xe7, 0x5a, 0xe5, 0xdd, 0xf2,
	0x5e, 0x93, 0x56, 0x3c, 0x97, 0x10, 0x58, 0x0a, 0x59, 0xc0, 0xad, 0x0a, 0x22, 0xf8, 0x4d, 0xb6,
	0xa1, 0xce, 0x2e, 0x59, 0xc2, 0x62, 0xab, 0x8a, 0xa8, 0x96, 0xc8, 0x26, 0xd4, 0x7c, 0x7e, 0xc9,
	0x7d, 0x6b, 0x69, 0xb7, 0xbc, 0x57, 0xa3, 0x4a, 0x90, 0x1e, 0x1c, 0xd6, 0xef, 0x59, 0xb5, 0xdd,
	0xf2, 0x5e, 0x95, 0xe2, 0x37, 0x59, 0x87, 0x2a, 0x1f, 0x46, 0x56, 0x1d, 0x21, 0xf9, 0x29, 0x7d,
	0x06, 0x6c, 0xf8, 0x64, 0x18, 0x59, 0xcb, 0x08, 0x6a, 0x89, 0xdc, 0x86, 0xd5, 0x80, 0x0d, 0x29,
	0xef, 0xf3, 0xf8, 0x92, 0x9f, 0xfa, 0x22, 0xb1, 0x1a, 0xe8, 0x7c, 0x02, 0x25, 0xbb, 0xd0, 0x0a,
	0xd8, 0xf0, 0x84, 0x3b, 0x17, 0x48, 0x6a, 0x22, 0xc9, 0x84, 0xec, 0x87, 0xd0, 0x64, 0xbe, 0xff,
	0x5a, 0x6d, 0xf3, 0x0e, 0x2c, 0xab, 0x0d, 0xf7, 0xad, 0xf2, 0x6e, 0x75, 0xaf, 0x75, 0x40, 0xee,
	0x9a, 0x19, 0x42, 0x15, 0x1d, 0x51, 0xec, 0xdf, 0xcb, 0x72, 0x0f, 0xb1, 0x9b, 0xcb, 0xce, 0x26,
	0xd4, 0xbc, 0x80, 0x75, 0x47, 0xe9, 0x51, 0x82, 0x44, 0xa3, 0xd8, 0x73, 0x38, 0xa6, 0xa7, 0x4a,
	0x95, 0x30, 0x25, 0x3b, 0xeb, 0x50, 0x65, 0xc9, 0x85, 0x4e, 0x8e, 0xfc, 0x94, 0x88, 0xcb, 0xcf,
	0x47, 0xb9, 0x71, 0xf9, 0xb9, 0xb4, 0x74, 0x84, 0x2f, 0x62, 0x4c, 0x4d, 0x8d, 0x2a, 0x21, 0xad,
	0x4c, 0x23, 0xab, 0x8c, 0xfd, 0x19, 0x2c, 0x33, 0xdf, 0x3f, 0x96, 0xa1, 0xde, 0x86, 0x9a, 0x0c,
	0x79, 0xb4, 0xbf, 0x75, 0x73, 0x7f, 0xf2, 0x93, 0x2a, 0xb5, 0xed, 0x41, 0x5b, 0x6d, 0xf3, 0x30,
	0x74, 0xd1, 0x70, 0x1f, 0xea, 0x8e, 0xef, 0xf1, 0x30, 0xc1, 0x7d, 0x16, 0x67, 0x46, 0x33, 0xc8,
	0x1d, 0x68, 0x48, 0xe5, 0x09, 0x4b, 0x18, 0xa6, 0xa0, 0x68, 0x9d, 0x94, 0x61, 0xbf, 0x33, 0x96,
	0xc2, 0xa2, 0xed, 0x41, 0xed, 0xd5, 0x55, 0xc8, 0xe3, 0x19, 0x2b, 0x29, 0x02, 0xd9, 0x81, 0x46,
	0xdf, 0x17, 0xc9, 0xdb, 0xeb, 0x48, 0xe5, 0xba, 0x46, 0x53, 0xd9, 0xfe, 0x15, 0xa0, 0xe5, 0x8b,
	0xb3, 0xb3, 0xeb, 0xd3, 0x24, 0xe6, 0x2c, 0x20, 0x5f, 0x00, 0x28, 0xe3, 0xef, 0x85, 0x17, 0x4e,
	0x77, 0xdd, 0x29, 0x51, 0x83, 0x97, 0x59, 0x3d, 0xe7, 0xe7, 0x89, 0xde, 0xcc, 0x4c, 0x2b, 0xc9,
	0x23, 0x5f, 0x02, 0x38, 0x31, 0x67, 0x09, 0xa7, 0x42, 0x04, 0x58, 0xef, 0xd6, 0xc1, 0xa6, 0x69,
	0x15, 0x0b, 0x11, 0xc8, 0xcd, 0x4b, 0xbb, 0x8c, 0x49, 0xf6, 0x61, 0xad, 0xdf, 0x13, 0x11, 0xe5,
	0xe7, 0x31, 0xef, 0xf7, 0xde, 0x7a, 0x01, 0x57, 0xc7, 0xa2, 0x53, 0xa2, 0x93, 0x0a, 0x62, 0x43,
	0xcb, 0x80, 0xf0, 0xa8, 0x34, 0x3a, 0x25, 0x6a, 0x82, 0x32, 0x8e, 0x2e, 0x4f, 0x5e, 0x85, 0x2a,
	0x8e, 0xfa, 0xec, 0x38, 0x32, 0x26, 0xf9, 0x0a, 0x5a, 0x5d, 0x9e, 0x1c, 0xfa, 0xbe, 0x94, 0xfa,
	0x78, 0xc0, 0x5a, 0x07, 0x37, 0x4c, 0x43, 0xa6, 0x74, 0x72, 0x41, 0x83, 0x49, 0x1e, 0x43, 0x5b,
	0x89, 0xaf, 0xf5, 0x35, 0x6a, 0xa0, 0xe9, 0xd6, 0x84, 0xe9, 0xeb, 0x51, 0xd2, 0xc6, 0xd9, 0xe4,
	0x01, 0xac, 0xa8, 0x28, 0x54, 0x2e, 0xf1, 0xbe, 0x4e, 0xcb, 0xf7, 0x18, 0x93, 0x1c, 0xc1, 0x86,
	0xfa, 0x3a, 0x1d, 0x38, 0x0e, 0xef, 0xf7, 0xb1, 0xc8, 0x30, 0xc3, 0x3c, 0x4f, 0xcf, 0xf9, 0xc0,
	0x92, 0xb7, 0x16, 0xf6, 0x81, 0x95, 0x7f, 0x01, 0x44, 0x84, 0x5c, 0xed, 0xe7, 0xbd, 0x97, 0xf4,
	0x8e, 0xf1, 0xb2, 0xad, 0xa0, 0x93, 0x8f, 0xf2, 0x4e, 0x52, 0x4a, 0xa7, 0x44, 0x0b, 0x0c, 0xc9,
	0x31, 0x6c, 0xe8, 0x9b, 0xfb, 0x5d, 0x78, 0xda, 0x13, 0x51, 0xe4, 0x85, 0x5d, 0xab, 0x5d, 0x58,
	0x0e, 0x49, 0x92, 0x31, 0xe5, 0xf8, 0xe4, 0x21, 0x34, 0x45, 0x78, 0x34, 0xb8, 0x96, 0xb0, 0xb5,
	0x8a, 0xc6, 0x1f, 0xe6, 0x43, 0xd1, 0x17, 0xbd, 0x53, 0xa2, 0x19, 0x9b, 0xdc, 0x82, 0x15, 0x11,
	0xca, 0xaf, 0x23, 0x31, 0xe8, 0xf6, 0x12, 0x6b, 0x4d, 0x9f, 0xb2, 0x31, 0x94, 0x3c, 0x02, 0x10,
	0xe1, 0x29, 0x57, 0x0b, 0x5b, 0xeb, 0xf3, 0x57, 0x30, 0xe8, 0x64, 0x57, 0x1a, 0xcb, 0xaf, 0x53,
	0xe1, 0xbb, 0xd6, 0x86, 0x5e, 0xc0, 0xc0, 0xc8, 0x31, 0xac, 0x2a, 0x29, 0x7d, 0xc7, 0xc9, 0x8c,
	0x25, 0x24, 0xa1, 0x53, 0xa2, 0x13, 0x26, 0xe4, 0x0e, 0xac, 0x8b, 0x50, 0x57, 0xea, 0xd0, 0x45,
	0x96, 0x75, 0x43, 0x2f, 0x96, 0xd3, 0x90, 0x43, 0x68, 0x33, 0x17, 0xa3, 0x7d, 0x2b, 0xa4, 0x0b,
	0x6b, 0x73, 0xfe, 0xa6, 0xc6, 0x2d, 0xc8, 0x33, 0x20, 0x31, 0x0f, 0xc4, 0x25, 0x97, 0xd8, 0xd3,
	0x58, 0x04, 0xe8, 0x67, 0x6b, 0xbe, 0x9f, 0x02, 0x33, 0x72, 0x0c, 0xc0, 0x87, 0xce, 0x0b, 0xde,
	0xef, 0xcb, 0xb6, 0xb2, 0x8d, 0x4e, 0x3e, 0x31, 0x9d, 0xf0, 0xa1, 0xc3, 0xa3, 0xc4, 0x13, 0xe1,
	0x93, 0x38, 0x16, 0xb1, 0x26, 0xca, 0x3c, 0x66, 0x66, 0x47, 0xcb, 0x50, 0xe3, 0x97, 0x3c, 0x4c,
	0xec, 0x9f, 0x2b, 0xd0, 0xfa, 0x71, 0xc0, 0x07, 0x5c, 0x3f, 0x8d, 0x47, 0xb0, 0x21, 0xc2, 0x1f,
	0x84, 0x17, 0xbe, 0x67, 0x5e, 0xe2, 0x85, 0x5d, 0x7c, 0x2d, 0x66, 0xbd, 0x90, 0x79, 0xba, 0xf2,
	0x21, 0xaf, 0x80, 0xe9, 0xa3, 0x32, 0xdb, 0xc7, 0x04, 0x9d, 0x7c, 0x03, 0x6d, 0x11, 0x2a, 0xde,
	0x53, 0x31, 0x08, 0xdd, 0x39, 0x2f, 0xe7, 0x38, 0x59, 0x55, 0x58, 0x01, 0x2f, 0x45, 0xa2, 0x1c,
	0x2c, 0x65, 0x15, 0x1e, 0xd7, 0x64, 0xc9, 0xf8, 0xb3, 0x0c, 0x6b, 0x13, 0x97, 0x51, 0x76, 0x20,
	0x31, 0xaf, 0x03, 0x21, 0x81, 0xdc, 0x82, 0x25, 0x57, 0xd6, 0xb5, 0x32, 0xa5, 0x9d, 0xa2, 0x56,
	0x36, 0x44, 0x97, 0x47, 0xbe, 0xb8, 0xe6, 0x72, 0x4f, 0xc5, 0xcc, 0x94, 0x41, 0xf6, 0x61, 0x39,
	0x56, 0x33, 0x8c, 0xb5, 0x34, 0x85, 0x3c, 0x22, 0xc8, 0xd1, 0xa3, 0x17, 0xe9, 0x39, 0xa1, 0xd2,
	0x8b, 0xec, 0x67, 0x40, 0xd2, 0xf7, 0x35, 0xdb, 0xcf, 0xfd, 0xc9, 0xb9, 0x66, 0xd6, 0x53, 0x94,
	0x0d, 0x38, 0xbf, 0x54, 0xa1, 0x31, 0xca, 0x77, 0x6e, 0xc8, 0xd9, 0x51, 0xba, 0x97, 0xd9, 0x18,
	0x98, 0xca, 0xe6, 0x7a, 0x4b, 0x8b, 0xaf, 0x47, 0x3e, 0x86, 0x66, 0xc0, 0x86, 0x2a, 0x78, 0xdc,
	0x53, 0x8d, 0x66, 0x00, 0xb9, 0x05, 0xed, 0x54, 0xc0, 0xbb, 0x54, 0x47, 0xc6, 0x38, 0x48, 0x0e,
	0x60, 0x33, 0x60, 0xc3, 0xe3, 0x41, 0x1c, 0xf3, 0x30, 0x39, 0xc1, 0x94, 0x06, 0x72, 0x6a, 0x51,
	0x43, 0x52, 0xa1, 0x4e, 0x7b, 0x36, 0xc8, 0x8d, 0xd4, 0xb3, 0xc1, 0xda, 0x87, 0x75, 0xce, 0x9c,
	0x9e, 0xee, 0x5d, 0x9c, 0xf9, 0x49, 0x0f, 0x1b, 0x54, 0x95, 0xe6, 0x70, 0x62, 0xc3, 0x8a, 0x23,
	0x84, 0x7f, 0x22, 0xae, 0x42, 0xec, 0xe2, 0x80, 0x0e, 0xc7, 0x30, 0x72, 0x17, 0xea, 0x31, 0xbf,
	0x92, 0x2f, 0xa6, 0xea, 0x31, 0xdb, 0x93, 0xc7, 0x9c, 0xa2, 0x96, 0x6a, 0x96, 0xfd, 0x13, 0x40,
	0x86, 0x92, 0x7b, 0x80, 0xa3, 0xba, 0x92, 0xa6, 0x4e, 0x73, 0x06, 0x87, 0xdc, 0x94, 0x16, 0xfd,
	0x9e, 0xb6, 0xa8, 0x60, 0xe4, 0x06, 0x22, 0xb3, 0xcf, 0x87, 0x91, 0x56, 0xab, 0x19, 0x35, 0x03,
	0xec, 0xfb, 0x38, 0x43, 0xea, 0x29, 0xa5, 0x16, 0xe3, 0x5c, 0xa0, 0x56, 0x2d, 0xbc, 0x9e, 0x54,
	0x51, 0xec, 0xdf, 0xca, 0x40, 0x54, 0x79, 0x15, 0x81, 0xf2, 0xfe, 0xc0, 0x4f, 0xfe, 0xd3, 0x05,
	0x6b, 0xbb, 0x4c, 0xce, 0xcf, 0x94, 0x3b, 0xdc, 0xbb, 0xe4, 0x3a, 0xf0, 0x71, 0x50, 0x1e, 0x46,
	0x1e, 0xf2, 0xe0, 0xfa, 0x30, 0xb9, 0xd0, 0xa1, 0xa7, 0xb2, 0xd4, 0xa1, 0xab, 0x13, 0x7e, 0x8e,
	0xef, 0x41, 0x95, 0xa6, 0xb2, 0xfd, 0x57, 0x19, 0x9a, 0x3c, 0x74, 0x75, 0x54, 0xfb, 0x50, 0xbf,
	0xf2, 0xc2, 0xd9, 0x61, 0x69, 0x06, 0xe9, 0xc0, 0x1a, 0xf3, 0x7d, 0x73, 0x53, 0xfa, 0x0d, 0xb8,
	0x99, 0x37, 0x32, 0x59, 0x74, 0xd2, 0x4c, 0xd6, 0xe5, 0xdc, 0x67, 0x5d, 0xed, 0xa4, 0x8a, 0x27,
	0xc5, 0x40, 0x8c, 0x73, 0xb2, 0xb4, 0xd0, 0x39, 0x79, 0x03, 0x5b, 0xe9, 0x13, 0x30, 0xb6, 0xd0,
	0x03, 0x7c, 0x57, 0x06, 0x7e, 0x32, 0xaa, 0xdc, 0xbc, 0x50, 0x47, 0x74, 0xfb, 0x9f, 0x9a, 0x3a,
	0x7b, 0xba, 0x5f, 0x3c, 0x2e, 0x18, 0xa5, 0xe7, 0x0c, 0x37, 0xe6, 0x4c, 0xfd, 0xb8, 0x60, 0xa6,
	0x5e, 0xcc, 0x1c, 0x47, 0xac, 0xaf, 0xe5, 0x4c, 0x22, 0x0f, 0xe2, 0xbb, 0xc8, 0x65, 0x09, 0x9f,
	0xd3, 0x24, 0xc6, 0xb8, 0xe4, 0x26, 0x34, 0x1d, 0x31, 0x08, 0x13, 0x79, 0x09, 0xd3, 0xd1, 0x3a,
	0x83, 0xc8, 0xb7, 0xb0, 0x72, 0x66, 0x96, 0xb4, 0x96, 0xef, 0xb4, 0x85, 0xb9, 0x95, 0x0b, 0x99,
	0x86, 0xe4, 0x53, 0x59, 0x34, 0x74, 0x51, 0xcf, 0x4f, 0xc0, 0xe9, 0x89, 0xeb, 0x94, 0xa8, 0xa6,
	0x11, 0x0b, 0xea, 0x22, 0x3c, 0x89, 0xd9, 0x95, 0x7a, 0xa9, 0xa4, 0x46, 0xc9, 0x72, 0xba, 0x52,
	0xad, 0x01, 0xa7, 0xab, 0xc6, 0x02, 0xd3, 0x55, 0x46, 0x97, 0xc6, 0x91, 0xe7, 0x5c, 0x0c, 0x22,
	0x34, 0x6e, 0x2e, 0x60, 0x9c, 0xd1, 0x27, 0x7e, 0x3e, 0xc0, 0xc2, 0x3f, 0x1f, 0xc6, 0xa7, 0x95,
	0xd6, 0xff, 0x9a, 0x56, 0x46, 0xfd, 0xe5, 0xa9, 0xcf, 0xba, 0x38, 0x3f, 0xd7, 0x68, 0x2a, 0xcb,
	0x9f, 0xf5, 0xba, 0x67, 0xa0, 0xba, 0xad, 0x7e, 0xd6, 0x1b, 0x90, 0xbc, 0x54, 0xaa, 0x1e, 0x48,
	0x58, 0x55, 0x97, 0x2a, 0x43, 0xc8, 0x36, 0xd4, 0x3d, 0x17, 0xb7, 0xb5, 0xa6, 0xfe, 0xac, 0x50,
	0x52, 0x36, 0x16, 0x78, 0xb0, 0x55, 0x18, 0x25, 0xb6, 0x81, 0x91, 0x62, 0xb4, 0x45, 0xd5, 0x15,
	0x73, 0xb8, 0x7c, 0xbc, 0x52, 0x0c, 0x03, 0x51, 0x3f, 0x52, 0xc7, 0xc1, 0x83, 0x3f, 0x2a, 0xb0,
	0x91, 0x25, 0xe7, 0x94, 0xc7, 0x97, 0x9e, 0xc3, 0xc9, 0x23, 0x58, 0xcb, 0xc0, 0xe7, 0xa2, 0xeb,
	0x85, 0xa4, 0xe0, 0x3d, 0xda, 0x29, 0xc0, 0xec, 0x12, 0x79, 0x0e, 0x9b, 0x19, 0x4c, 0xb3, 0x9b,
	0x9b, 0x7b, 0x3b, 0x14, 0xbe, 0x33, 0x05, 0xb7, 0x4b, 0x7b, 0xe5, 0x7b, 0x65, 0xf2, 0x0a, 0xb6,
	0xcc, 0x50, 0xb2, 0xdf, 0xd4, 0x1f, 0x98, 0x66, 0xc6, 0x8f, 0xed, 0x9d, 0x69, 0x8a, 0x22, 0x87,
	0x6f, 0x8c, 0x49, 0x74, 0xcc, 0xce, 0x18, 0x51, 0x77, 0xa6, 0x29, 0x94, 0xc3, 0xb3, 0x3a, 0xfe,
	0x7b, 0xf5, 0xf9, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x71, 0x61, 0x0d, 0x8c, 0xd1, 0x12, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CardBattleServiceClient is the client API for CardBattleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CardBattleServiceClient interface {
	CardBattleLogin(ctx context.Context, in *Player, opts ...grpc.CallOption) (*Player, error)
	CardBattleRoomStream(ctx context.Context, opts ...grpc.CallOption) (CardBattleService_CardBattleRoomStreamClient, error)
	CardBattleLobbyStream(ctx context.Context, opts ...grpc.CallOption) (CardBattleService_CardBattleLobbyStreamClient, error)
	CardBattleQueueStream(ctx context.Context, opts ...grpc.CallOption) (CardBattleService_CardBattleQueueStreamClient, error)
}

type cardBattleServiceClient struct {
	cc *grpc.ClientConn
}

func NewCardBattleServiceClient(cc *grpc.ClientConn) CardBattleServiceClient {
	return &cardBattleServiceClient{cc}
}

func (c *cardBattleServiceClient) CardBattleLogin(ctx context.Context, in *Player, opts ...grpc.CallOption) (*Player, error) {
	out := new(Player)
	err := c.cc.Invoke(ctx, "/cardBattle.cardBattleService/cardBattleLogin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardBattleServiceClient) CardBattleRoomStream(ctx context.Context, opts ...grpc.CallOption) (CardBattleService_CardBattleRoomStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CardBattleService_serviceDesc.Streams[0], "/cardBattle.cardBattleService/cardBattleRoomStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &cardBattleServiceCardBattleRoomStreamClient{stream}
	return x, nil
}

type CardBattleService_CardBattleRoomStreamClient interface {
	Send(*RoomStream) error
	Recv() (*RoomStream, error)
	grpc.ClientStream
}

type cardBattleServiceCardBattleRoomStreamClient struct {
	grpc.ClientStream
}

func (x *cardBattleServiceCardBattleRoomStreamClient) Send(m *RoomStream) error {
	return x.ClientStream.SendMsg(m)
}

func (x *cardBattleServiceCardBattleRoomStreamClient) Recv() (*RoomStream, error) {
	m := new(RoomStream)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *cardBattleServiceClient) CardBattleLobbyStream(ctx context.Context, opts ...grpc.CallOption) (CardBattleService_CardBattleLobbyStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CardBattleService_serviceDesc.Streams[1], "/cardBattle.cardBattleService/cardBattleLobbyStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &cardBattleServiceCardBattleLobbyStreamClient{stream}
	return x, nil
}

type CardBattleService_CardBattleLobbyStreamClient interface {
	Send(*LobbyStream) error
	Recv() (*LobbyStream, error)
	grpc.ClientStream
}

type cardBattleServiceCardBattleLobbyStreamClient struct {
	grpc.ClientStream
}

func (x *cardBattleServiceCardBattleLobbyStreamClient) Send(m *LobbyStream) error {
	return x.ClientStream.SendMsg(m)
}

func (x *cardBattleServiceCardBattleLobbyStreamClient) Recv() (*LobbyStream, error) {
	m := new(LobbyStream)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *cardBattleServiceClient) CardBattleQueueStream(ctx context.Context, opts ...grpc.CallOption) (CardBattleService_CardBattleQueueStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CardBattleService_serviceDesc.Streams[2], "/cardBattle.cardBattleService/cardBattleQueueStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &cardBattleServiceCardBattleQueueStreamClient{stream}
	return x, nil
}

type CardBattleService_CardBattleQueueStreamClient interface {
	Send(*QueueStream) error
	Recv() (*QueueStream, error)
	grpc.ClientStream
}

type cardBattleServiceCardBattleQueueStreamClient struct {
	grpc.ClientStream
}

func (x *cardBattleServiceCardBattleQueueStreamClient) Send(m *QueueStream) error {
	return x.ClientStream.SendMsg(m)
}

func (x *cardBattleServiceCardBattleQueueStreamClient) Recv() (*QueueStream, error) {
	m := new(QueueStream)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CardBattleServiceServer is the server API for CardBattleService service.
type CardBattleServiceServer interface {
	CardBattleLogin(context.Context, *Player) (*Player, error)
	CardBattleRoomStream(CardBattleService_CardBattleRoomStreamServer) error
	CardBattleLobbyStream(CardBattleService_CardBattleLobbyStreamServer) error
	CardBattleQueueStream(CardBattleService_CardBattleQueueStreamServer) error
}

// UnimplementedCardBattleServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCardBattleServiceServer struct {
}

func (*UnimplementedCardBattleServiceServer) CardBattleLogin(ctx context.Context, req *Player) (*Player, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CardBattleLogin not implemented")
}
func (*UnimplementedCardBattleServiceServer) CardBattleRoomStream(srv CardBattleService_CardBattleRoomStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method CardBattleRoomStream not implemented")
}
func (*UnimplementedCardBattleServiceServer) CardBattleLobbyStream(srv CardBattleService_CardBattleLobbyStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method CardBattleLobbyStream not implemented")
}
func (*UnimplementedCardBattleServiceServer) CardBattleQueueStream(srv CardBattleService_CardBattleQueueStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method CardBattleQueueStream not implemented")
}

func RegisterCardBattleServiceServer(s *grpc.Server, srv CardBattleServiceServer) {
	s.RegisterService(&_CardBattleService_serviceDesc, srv)
}

func _CardBattleService_CardBattleLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Player)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardBattleServiceServer).CardBattleLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cardBattle.cardBattleService/CardBattleLogin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardBattleServiceServer).CardBattleLogin(ctx, req.(*Player))
	}
	return interceptor(ctx, in, info, handler)
}

func _CardBattleService_CardBattleRoomStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CardBattleServiceServer).CardBattleRoomStream(&cardBattleServiceCardBattleRoomStreamServer{stream})
}

type CardBattleService_CardBattleRoomStreamServer interface {
	Send(*RoomStream) error
	Recv() (*RoomStream, error)
	grpc.ServerStream
}

type cardBattleServiceCardBattleRoomStreamServer struct {
	grpc.ServerStream
}

func (x *cardBattleServiceCardBattleRoomStreamServer) Send(m *RoomStream) error {
	return x.ServerStream.SendMsg(m)
}

func (x *cardBattleServiceCardBattleRoomStreamServer) Recv() (*RoomStream, error) {
	m := new(RoomStream)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _CardBattleService_CardBattleLobbyStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CardBattleServiceServer).CardBattleLobbyStream(&cardBattleServiceCardBattleLobbyStreamServer{stream})
}

type CardBattleService_CardBattleLobbyStreamServer interface {
	Send(*LobbyStream) error
	Recv() (*LobbyStream, error)
	grpc.ServerStream
}

type cardBattleServiceCardBattleLobbyStreamServer struct {
	grpc.ServerStream
}

func (x *cardBattleServiceCardBattleLobbyStreamServer) Send(m *LobbyStream) error {
	return x.ServerStream.SendMsg(m)
}

func (x *cardBattleServiceCardBattleLobbyStreamServer) Recv() (*LobbyStream, error) {
	m := new(LobbyStream)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _CardBattleService_CardBattleQueueStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CardBattleServiceServer).CardBattleQueueStream(&cardBattleServiceCardBattleQueueStreamServer{stream})
}

type CardBattleService_CardBattleQueueStreamServer interface {
	Send(*QueueStream) error
	Recv() (*QueueStream, error)
	grpc.ServerStream
}

type cardBattleServiceCardBattleQueueStreamServer struct {
	grpc.ServerStream
}

func (x *cardBattleServiceCardBattleQueueStreamServer) Send(m *QueueStream) error {
	return x.ServerStream.SendMsg(m)
}

func (x *cardBattleServiceCardBattleQueueStreamServer) Recv() (*QueueStream, error) {
	m := new(QueueStream)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _CardBattleService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cardBattle.cardBattleService",
	HandlerType: (*CardBattleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "cardBattleLogin",
			Handler:    _CardBattleService_CardBattleLogin_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "cardBattleRoomStream",
			Handler:       _CardBattleService_CardBattleRoomStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "cardBattleLobbyStream",
			Handler:       _CardBattleService_CardBattleLobbyStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "cardBattleQueueStream",
			Handler:       _CardBattleService_CardBattleQueueStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "cardBattle.proto",
}
